GET http://localhost:4000/api/user/word
###
POST http://localhost:4000/api/user/word
Content-Type: application/json

{
    "name": "abide by",
    "mean": "to comply with; to conform",
    "example": "<p>a. The landlord and tenant were in agreement that the rent should be prorated to the middle of the month.<br>\nb. According to the agreement, the caterer will also supply the flowers for the event.</p>",
    "book": "600 Toeic"
}
###
PUT http://localhost:4000/api/user/word?id=1
Content-Type: application/json

{
    "name":"private receiption",
    "mean":"cuộc tiếp đón riêng",
    "useto":"i have a private receiption in this morning"
}
###
DELETE http://localhost:4000/api/user/word?id=1